# ⚠️ THIS PROJECT IS DEPRECATED - DO NOT USE
# All semantic views have been moved to dbt_o2c/models/semantic_views/
# Build from dbt_o2c instead!

name: 'dbt_o2c_semantic_DEPRECATED'
version: '0.0.0-deprecated'
config-version: 2

profile: 'snowflake_o2c_INVALID'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Snowflake semantic view configuration
  semantic_view_schema: 'o2c_semantic_views'

models:
  dbt_o2c_semantic:
    semantic_views:
      +materialized: semantic_view  # Uses dbt_semantic_view package
      +schema: o2c_semantic_views
      +tags: ['semantic_view', 'cortex_analyst']
      +access: public

