name: 'dbt_o2c_semantic'
version: '1.0.0'
config-version: 2

profile: 'snowflake_o2c'

model-paths: ["models"]
target-path: "target"

vars:
  # Snowflake semantic view configuration
  semantic_view_schema: 'o2c_semantic_views'

models:
  dbt_o2c_semantic:
    semantic_views:
      +materialized: view  # Semantic views are special Snowflake objects
      +schema: o2c_semantic_views
      +tags: ['semantic_view', 'cortex_analyst']

