name: 'dbt_o2c_semantic'
version: '1.0.0'
config-version: 2

profile: 'snowflake_o2c'

model-paths: ["models"]
target-path: "target"

vars:
  # Enable semantic view generation
  enable_semantic_views: true

models:
  dbt_o2c_semantic:
    # Semantic views will be materialized as Snowflake DYNAMIC TABLEs
    semantic_views:
      +materialized: dynamic_table
      +schema: o2c_semantic_views
      +target_lag: '1 hour'
      +tags: ['o2c', 'semantic', 'dynamic_table']
      +access: public

