# This file should be copied to ~/.dbt/profiles.yml
# Then update with your Snowflake credentials

dbt_foundation:
  outputs:
    dev:
      type: snowflake
      account: <your_account>  # e.g., xy12345.us-east-1
      user: <your_username>
      password: <your_password>  # Or use authenticator: externalbrowser
      role: DBT_ROLE
      database: EDW
      warehouse: COMPUTE_WH
      schema: DEV_<YOUR_INITIALS>  # e.g., DEV_JD
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_foundation_dev
      
    prod:
      type: snowflake
      account: <your_account>
      user: <service_account>
      password: <service_password>
      role: DBT_ROLE
      database: EDW
      warehouse: COMPUTE_WH
      schema: DBT_SHARED  # Production schema
      threads: 8
      client_session_keep_alive: True
      query_tag: dbt_foundation_prod
  
  target: dev

# Notes:
# 1. Copy this file to ~/.dbt/profiles.yml
# 2. Replace <placeholders> with actual values
# 3. For security, consider using environment variables:
#    password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
# 4. Or use SSO: authenticator: externalbrowser

